### PR TITLE
fix(upgrade): correctly deal with upgrade

### LINKED ISSUE #1312: Add test to ensure we deal with upgrade to http2
See #1227.

### PR DESCRIPTION
**Pull request by bassosimone**
While there, add regress tests.

Closes #1312.

### CODE REVIEW

File: include/private/http/response_parser.hpp [hunk 1]
```diff
@@ -181,9 +181,25 @@ class ResponseParserNg : public NonCopyable, public NonMovable {
...
+        //
+        // This fixes for example the `http://aseansec.org/` URL.
+        //
+        // I am going to keep the code below commented out and this comment
+        // so the choices I made are clear and documented.
+        /*
         if (parser_.upgrade) {
             throw UpgradeError();
         }
+        */
```
Comment (hellais) [inline include/private/http/response_parser.hpp]: Maybe then you want to just delete the code in here and move the comment above into the commit message?

**Comment by bassosimone** [comment]
Note: the unit tests fail because I need to remove (or comment out) the test that was checking that `UPGRADE` was actually thrown by the parser.

File: include/private/http/response_parser.hpp (hunk 1 above)
Comment (bassosimone) [reply include/private/http/response_parser.hpp]: Yeah, makes sense!

Comment (hellais) [reply include/private/http/response_parser.hpp]: Yes I agree with this fix. Actually `Upgrade` is used to "kind of" advertise support for HTTP2 (or spdy) so in those cases the client knows it can use it (like you say "informational"). Maybe in the future we want to also support HTTP2 so maybe it's worth referencing this commit in that ticket to know the point of the code where that logic should/could be hooked.

**Comment by bassosimone** [comment]
Squashing and merging!
