### PR TITLE
fix(error_or): make construction unambiguous

### LINKED ISSUE #1509: Fix ErrorOr<bool> vs. bool
As discovered  by @joelanders in #1498

### PR DESCRIPTION
**Pull request by bassosimone**
Depends on #1529. See 93d93f098f02781605f236ef208c48e63193f9ca for the individual commit. Closes #1509.

- - - 

This diff is a response to @joelanders observation that sometimes
making an ErrorOr was leading to ambiguity.

The way in which I implemented it was that I removed all the
partial constructors, so now you always implement returning
ErrorOr like when returning a tuple. Which is more or less the
thing we're doing anyway. And also is more readable.

### CODE REVIEW

**Comment by bassosimone** [comment]
Uhm, I see that tests are failing. I'll try to fix that. This PR seems to be the culprit.

**Comment by bassosimone** [comment]
Added the "please preserve history" tag because I have fixed a number of minor build related issues as part of this PR. As such, it would probably make sense to avoid squashing this.

File: src/libmeasurement_kit/dns/libevent_query.hpp [hunk 1]
```diff
@@ -349,7 +349,8 @@ void libevent_query(QueryClass dns_class, QueryType dns_type, std::string name,
      *
      * This is not yet implemented in the libevent engine.
      */
-    ErrorOr<bool> also_cname = settings.get("dns/resolve_also_cname", false);
+    ErrorOr<bool> also_cname = settings.get_noexcept(
+            "dns/resolve_also_cname", false);
```
Comment (bassosimone) [inline src/libmeasurement_kit/dns/libevent_query.hpp]: This was actually a bug. The new code is correct.

File: src/libmeasurement_kit/dns/system_resolver.hpp [hunk 2]
```diff
@@ -49,7 +49,8 @@ void system_resolver(QueryClass dns_class, QueryType dns_type, std::string name,
      * When running OONI tests, we're interested to know not only the IPs
      * associated with a specific name, but also to the CNAME.
      */
-    ErrorOr<bool> also_cname = settings.get("dns/resolve_also_cname", false);
+    ErrorOr<bool> also_cname = settings.get_noexcept(
+            "dns/resolve_also_cname", false);
```
Comment (bassosimone) [inline src/libmeasurement_kit/dns/system_resolver.hpp]: This was actually a bug. The new code is correct.

File: src/libmeasurement_kit/http/request.cpp [hunk 3]
```diff
@@ -165,7 +165,8 @@ void request_recv_response(SharedPtr<Transport> txp,
 
 static void request_recv_response_start(SharedPtr<RequestRecvResponse> ctx) {
 
-    ErrorOr<bool> ignore_body = ctx->settings.get("http/ignore_body", false);
+    ErrorOr<bool> ignore_body = ctx->settings.get_noexcept(
+            "http/ignore_body", false);
```
Comment (bassosimone) [inline src/libmeasurement_kit/http/request.cpp]: This was actually a bug. The new code is correct.

File: src/libmeasurement_kit/ooni/templates.cpp [hunk 4]
```diff
@@ -101,7 +101,7 @@ void http_request(SharedPtr<Entry> entry, Settings settings, http::Headers heade
     (*entry)["socksproxy"] = nullptr;
 
     // Include the name of the agent, like ooni-probe does
-    ErrorOr<int> max_redirects = settings.get("http/max_redirects", 0);
+    ErrorOr<int> max_redirects = settings.get_noexcept("http/max_redirects", 0);
```
Comment (bassosimone) [inline src/libmeasurement_kit/ooni/templates.cpp]: This was actually a bug. The new code is correct.

File: src/measurement_kit/utils.cpp [hunk 5]
```diff
@@ -16,8 +18,8 @@ BaseTest &common_init(std::list<Callback<BaseTest &>> il, BaseTest &test) {
             fflush(stdout);
         })
         .on_overall_data_usage([](DataUsage du) {
-            printf("Overall data usage (bytes): %llu down - %llu up\n",
-                    du.down, du.up);
+            printf("Overall data usage (bytes): %" PRId64 " down - %"
+                    PRId64 " up\n", du.down, du.up);
```
Comment (bassosimone) [inline src/measurement_kit/utils.cpp]: This fixes a warning when building on Ubuntu on Windows. Not strictly related to the PR. If merging is not squashing, this would be included in master as a separate commit.

File: test/common/utils.cpp [hunk 6]
```diff
@@ -395,8 +395,8 @@ TEST_CASE("random_choice isn't obviously wrong") {
 }
 
 TEST_CASE("randomly_capitalize isn't obviously wrong") {
-    auto lower_string = "abcdefghij";
-    auto upper_string = "ABCDEFGHIJ";
+    auto lower_string = "abcdefghijklmnopqrstuvz";
+    auto upper_string = "ABCDEFGHIJKLMNOPQRSTUVZ";
```
Comment (bassosimone) [inline test/common/utils.cpp]: This is another, unrelated small fix that I committed on this PR to unbreak the build. Strictly speaking it can go into another PR, but if we don't squash it can as well go in with this PR.

**Comment by darkk** [comment]
LGTM :-|

**Comment by bassosimone** [comment]
@darkk thank you!
