### PR TITLE
ssl: refactor for readability, fix thread safety

### LINKED ISSUE #1296: ssl-related crash in iOS app
Except from crashlitics crash:

```
0  libsystem_kernel.dylib         0x1878e1014 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1879ab334 pthread_kill + 112
2  libsystem_c.dylib              0x1878559c4 abort + 140
3  libsystem_c.dylib              0x18782a53c basename_r + 314
4  ooniprobe                      0x10031b5d8 mk::ErrorOr<ssl_st*> mk::net::make_ssl<&(SSL_new)>(ssl_ctx_st*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 88
5  ooniprobe                      0x10031b540 mk::net::SslContext::get_client_ssl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 60
6  ooniprobe                      0x100309488 mk::net::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::Transport>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_3::operator()(mk::Error, mk::Var<mk::net::ConnectResult>) const + 2516
7  ooniprobe                      0x100308a4c void std::__1::__invoke_void_return_wrapper<void>::__call<mk::net::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::Transport>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_3&, mk::Error, mk::Var<mk::net::ConnectResult> >(mk::net::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::Transport>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_3&&&, mk::Error&&, mk::Var<mk::net::ConnectResult>&&) + 152
8  ooniprobe                      0x100308364 std::__1::__function::__func<mk::net::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::Transport>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_3, std::__1::allocator<mk::net::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::Transport>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_3>, void (mk::Error, mk::Var<mk::net::ConnectResult>)>::operator()(mk::Error&&, mk::Var<mk::net::ConnectResult>&&) + 76
9  ooniprobe                      0x1002ff0f4 std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>::operator()(mk::Error, mk::Var<mk::net::ConnectResult>) const + 180
10 ooniprobe                      0x100301160 mk::net::connect_logic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_1::operator()(mk::dns::ResolveHostnameResult) const::'lambda'(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)::operator()(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*) const + 1456
11 ooniprobe                      0x100300b68 void std::__1::__invoke_void_return_wrapper<void>::__call<mk::net::connect_logic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_1::operator()(mk::dns::ResolveHostnameResult) const::'lambda'(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)&, std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*>(mk::net::connect_logic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_1::operator()(mk::dns::ResolveHostnameResult) const::'lambda'(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)&&&, std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >&&, bufferevent*&&) + 372
12 ooniprobe                      0x100300638 std::__1::__function::__func<mk::net::connect_logic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_1::operator()(mk::dns::ResolveHostnameResult) const::'lambda'(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*), std::__1::allocator<mk::net::connect_logic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, mk::Var<mk::net::ConnectResult>)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::$_1::operator()(mk::dns::ResolveHostnameResult) const::'lambda'(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>::operator()(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >&&, bufferevent*&&) + 76
13 ooniprobe                      0x1002f40e0 std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>::operator()(std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*) const + 180
14 ooniprobe                      0x1002fc3d8 mk::net::connect_first_of(mk::Var<mk::net::ConnectResult>, int, std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>, unsigned long, mk::Var<std::__1::vector<mk::Error, std::__1::allocator<mk::Error> > >)::$_0::operator()(mk::Error, bufferevent*, double) const + 936
15 ooniprobe                      0x1002fbfe8 void std::__1::__invoke_void_return_wrapper<void>::__call<mk::net::connect_first_of(mk::Var<mk::net::ConnectResult>, int, std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>, unsigned long, mk::Var<std::__1::vector<mk::Error, std::__1::allocator<mk::Error> > >)::$_0&, mk::Error, bufferevent*, double>(mk::net::connect_first_of(mk::Var<mk::net::ConnectResult>, int, std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>, unsigned long, mk::Var<std::__1::vector<mk::Error, std::__1::allocator<mk::Error> > >)::$_0&&&, mk::Error&&, bufferevent*&&, double&&) + 152
16 ooniprobe                      0x1002fb934 std::__1::__function::__func<mk::net::connect_first_of(mk::Var<mk::net::ConnectResult>, int, std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>, unsigned long, mk::Var<std::__1::vector<mk::Error, std::__1::allocator<mk::Error> > >)::$_0, std::__1::allocator<mk::net::connect_first_of(mk::Var<mk::net::ConnectResult>, int, std::__1::function<void (std::__1::vector<mk::Error, std::__1::allocator<mk::Error> >, bufferevent*)>, mk::Settings, mk::Var<mk::Reactor>, mk::Var<mk::Logger>, unsigned long, mk::Var<std::__1::vector<mk::Error, std::__1::allocator<mk::Error> > >)::$_0>, void (mk::Error, bufferevent*, double)>::operator()(mk::Error&&, bufferevent*&&, double&&) + 92
17 ooniprobe                      0x1002f90d0 std::__1::function<void (mk::Error, bufferevent*, double)>::operator()(mk::Error, bufferevent*, double) const + 196
18 ooniprobe                      0x1002fa990 void mk::net::connect_base<&(mk::net::make_sockaddr_proxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, sockaddr_storage*, unsigned int*)), &(bufferevent_socket_new), &(bufferevent_set_timeouts), &(bufferevent_socket_connect)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, bufferevent*, double)>, double, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::'lambda'(mk::Error, bufferevent*)::operator()(mk::Error, bufferevent*) const + 740
19 ooniprobe                      0x1002fa668 void std::__1::__invoke_void_return_wrapper<void>::__call<void mk::net::connect_base<&(mk::net::make_sockaddr_proxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, sockaddr_storage*, unsigned int*)), &(bufferevent_socket_new), &(bufferevent_set_timeouts), &(bufferevent_socket_connect)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, bufferevent*, double)>, double, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::'lambda'(mk::Error, bufferevent*)&, mk::Error, bufferevent*>(void mk::net::connect_base<&(mk::net::make_sockaddr_proxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, sockaddr_storage*, unsigned int*)), &(bufferevent_socket_new), &(bufferevent_set_timeouts), &(bufferevent_socket_connect)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, bufferevent*, double)>, double, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::'lambda'(mk::Error, bufferevent*)&&&, mk::Error&&, bufferevent*&&) + 120
20 ooniprobe                      0x1002fa03c std::__1::__function::__func<void mk::net::connect_base<&(mk::net::make_sockaddr_proxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, sockaddr_storage*, unsigned int*)), &(bufferevent_socket_new), &(bufferevent_set_timeouts), &(bufferevent_socket_connect)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, bufferevent*, double)>, double, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::'lambda'(mk::Error, bufferevent*), std::__1::allocator<void mk::net::connect_base<&(mk::net::make_sockaddr_proxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, sockaddr_storage*, unsigned int*)), &(bufferevent_socket_new), &(bufferevent_set_timeouts), &(bufferevent_socket_connect)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::function<void (mk::Error, bufferevent*, double)>, double, mk::Var<mk::Reactor>, mk::Var<mk::Logger>)::'lambda'(mk::Error, bufferevent*)>, void (mk::Error, bufferevent*)>::operator()(mk::Error&&, bufferevent*&&) + 76
21 ooniprobe                      0x1002f38a4 std::__1::function<void (mk::Error, bufferevent*)>::operator()(mk::Error, bufferevent*) const + 180
22 ooniprobe                      0x1002f3484 mk_bufferevent_on_event + 104
23 ooniprobe                      0x100187e1c bufferevent_run_deferred_callbacks_locked + 172
24 ooniprobe                      0x100192e38 event_process_active_single_queue + 1220
25 ooniprobe                      0x10018f6fc event_process_active + 340
26 ooniprobe                      0x10018e99c event_base_loop + 728
27 ooniprobe                      0x10018e6b8 event_base_dispatch + 32
28 ooniprobe                      0x100279758 void mk::libevent::poller_loop<&(event_new), &(event_free), &(event_add), &(event_base_dispatch)>(mk::Var<event_base>, mk::libevent::Poller*) + 384
29 ooniprobe                      0x100279598 mk::libevent::Poller::run() + 52
30 ooniprobe                      0x1001e0380 mk::Reactor::loop() + 32
31 ooniprobe                      0x1001e0354 mk::Reactor::run_with_initial_event(std::__1::function<void ()>&&) + 72
32 ooniprobe                      0x1003f64e0 mk::AsyncRunner::start_background_thread(mk::Var<mk::Logger>)::'lambda'()::operator()() const + 136
33 ooniprobe                      0x1003f61a8 void* std::__1::__thread_proxy<std::__1::tuple<mk::AsyncRunner::start_background_thread(mk::Var<mk::Logger>)::'lambda'()> >(void*) + 276
34 libsystem_pthread.dylib        0x1879a975c _pthread_body + 240
35 libsystem_pthread.dylib        0x1879a966c _pthread_body + 282
36 libsystem_pthread.dylib        0x1879a6d84 thread_start + 4
```

### PR DESCRIPTION
**Pull request by bassosimone**
- Move all SSL code into the same file, to increase readability and
  to simplify reasoning about our SSL usage.

- Do not split implementation between classes and functions, rather
  use template classes for testability. This should increase readability
  and be closer to what a typical C++ programmer would expect.

- Write an explicit SSL cache rather than having an implicit one, which
  also increases the readability of SSL code.

- Use thread local storage for SSL cache, so to solve #1296.

- Add doxygen style comments.

Further details on specific implementation choices are provided in
comments added in the new code. Further comments in the PR.

Closes #1296.

### CODE REVIEW

**Comment by bassosimone** [comment]
The code currently does not compile because tests needs to be refactored as well. While refactoring tests, I will also make sure that we reach 100% coverage of SSL code. For now, I only smoke tested this diff running a single web_connectivity test, to make sure it was not exploding.

The creation of this pull request will cause #1296 to transition to `done` state. Will close when v0.7.1 is out.

File: include/measurement_kit/net/error.hpp [hunk 1]
```diff
@@ -37,7 +37,7 @@ MK_DEFINE_ERR(MK_ERR_NET(22), NotEnoughDataError, "not_enough_data")
 MK_DEFINE_ERR(MK_ERR_NET(23), MissingCaBundlePathError, "missing_ca_bundle_path")
 /* Error code not used; was the old BrokenPipeError */
 MK_DEFINE_ERR(MK_ERR_NET(25), SslNewError, "ssl_new_error")
-MK_DEFINE_ERR(MK_ERR_NET(26), SslCtxNewError, "ssl_ctx_net_error")
+MK_DEFINE_ERR(MK_ERR_NET(26), SslCtxNewError, "ssl_ctx_new_error")
```
Comment (bassosimone) [inline include/measurement_kit/net/error.hpp]: This _technically_ breaks the API. But, honestly, I don't think adding this to the `v0.7.1` backport will be an issue.

File: include/private/ext/tls_internal.h [hunk 2]
```diff
@@ -2,8 +2,8 @@
  * This is a mock of tls_internal.h filling out all the functions that are
  * called by tls_verify with mocks.
  */
-#ifndef SRC_EXT_TLS_INTERNAL_H
-#define SRC_EXT_TLS_INTERNAL_H
+#ifndef PRIVATE_EXT_TLS_INTERNAL_H
+#define PRIVATE_EXT_TLS_INTERNAL_H
```
Comment (bassosimone) [inline include/private/ext/tls_internal.h]: Here I just noticed the include guard needed to be updated.

File: include/private/net/libssl.hpp [hunk 3]
```diff
@@ -0,0 +1,327 @@
...
+/// Singleton for initializing SSL library.
+class Library : public HasGlobalFactory<Library> {
+  protected:
+    // Implementation note: since this lives as long as the application, it
+    // would be a bit pointless to cleanup things in the destructor.
+    Library() {
+        SSL_library_init();
+        ERR_load_crypto_strings();
+        SSL_load_error_strings();
+        OpenSSL_add_all_algorithms();
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Refactored from `initialize_ssl()`.

File: include/private/net/ssl_context_impl.hpp [hunk 4]
```diff
@@ -1,95 +0,0 @@
...
-}
-
-static void initialize_ssl() {
-    static bool ssl_initialized = false;
-    if (!ssl_initialized) {
-        SSL_library_init();
-        ERR_load_crypto_strings();
-        SSL_load_error_strings();
-        OpenSSL_add_all_algorithms();
-        ssl_initialized = true;
```
Comment (bassosimone) [inline include/private/net/ssl_context_impl.hpp]: Refactored as `libssl::Library::Library()`.

File: include/private/net/ssl_context_impl.hpp [hunk 5]
```diff
@@ -1,95 +0,0 @@
...
-ErrorOr<SSL *> make_ssl(SSL_CTX *ctx, std::string hostname) {
-    assert(ctx != nullptr);
-    SSL *ssl = SSL_new(ctx);
-    if (ssl == nullptr) {
-        warn("ssl: failed to call SSL_new");
-        return SslNewError();
-    }
-    SSL_set_tlsext_host_name(ssl, hostname.c_str());
-    return ssl;
-}
```
Comment (bassosimone) [inline include/private/net/ssl_context_impl.hpp]: Refactored as `libssl::Context::get_client_ssl()`

File: include/private/net/libssl.hpp [hunk 6]
```diff
@@ -0,0 +1,327 @@
...
+    ErrorOr<SSL *> get_client_ssl(std::string hostname, Var<Logger> logger) {
+        assert(ctx_ != nullptr);
+        SSL *ssl = SSL_new(ctx_);
+        if (ssl == nullptr) {
+            logger->warn("ssl: SSL_new failed");
+            return SslNewError();
+        }
+        SSL_set_tlsext_host_name(ssl, hostname.c_str());
+        return ssl;
+    }
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Refactored from `make_ssl()`.

File: include/private/net/libssl.hpp [hunk 7]
```diff
@@ -0,0 +1,327 @@
...
+#else
+            SSL_CTX_free(ctx);
+            return MissingCaBundlePathError();
+#endif
+        }
+        SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, nullptr);
+        Var<Context> context{new Context};
+        context->ctx_ = ctx;
+        return context;
+    }
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Refactored from `make_ssl_ctx()`

File: include/private/net/ssl_context_impl.hpp [hunk 8]
```diff
@@ -1,95 +0,0 @@
...
-        /* FALLTHROUGH */
-#else
-        SSL_CTX_free(ctx);
-        return MissingCaBundlePathError();
-#endif
-    }
-
-    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, nullptr);
-    return ctx;
-}
```
Comment (bassosimone) [inline include/private/net/ssl_context_impl.hpp]: Refactored to `libssl::Context::make()`

File: src/libmeasurement_kit/net/ssl_context.cpp [hunk 9]
```diff
@@ -1,37 +0,0 @@
...
-        }
-        singleton->ctx = *maybe_ctx;
-        singleton->ca_bundle_path = path;
-        /* FALLTHROUGH */
-    }
-    return singleton;
-}
-
-SslContext::~SslContext() {
-    SSL_CTX_free(ctx);
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/ssl_context.cpp]: Refactored to `libssl::Context::~Context()`

File: include/private/net/libssl.hpp [hunk 10]
```diff
@@ -0,0 +1,327 @@
...
+            return SslNewError();
+        }
+        SSL_set_tlsext_host_name(ssl, hostname.c_str());
+        return ssl;
+    }
+
+    /// Destructor.
+    ~Context() {
+        assert(ctx_ != nullptr);
+        SSL_CTX_free(ctx_);
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Refactored from `SslContext::~SslContext()`

File: include/private/net/libssl.hpp [hunk 11]
```diff
@@ -0,0 +1,327 @@
...
+    SSL_CTX *ctx_ = nullptr;
+};
+
+/*!
+    \brief Thread-safe cache for constructing `SSL *` objects.
+
+    \remark Unless you need low-level control, you SHOULD really use
+    this API for creating an `SSL *` when connecting to an host.
+*/
+template <size_t max_cache_size = 64> class Cache {
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: This is not refactored, but rather newly written code functionally equivalent to `make_ssl_ctx()` but more clear.

File: include/private/net/libssl.hpp [hunk 12]
```diff
@@ -0,0 +1,327 @@
...
+        logger->warn("ssl: got no certificate");
+        return SslNoCertificateError();
+    }
+    auto err = tls_check_name(nullptr, server_cert, hostname.c_str());
+    X509_free(server_cert); // Make sure we don't leak memory
+    if (err != 0) {
+        logger->warn("ssl: got invalid hostname");
+        return SslInvalidHostnameError();
+    }
+    return NoError();
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Refactored from `connect_ssl()`. For test-ability and clarity.

File: src/libmeasurement_kit/net/connect.cpp [hunk 13]
```diff
@@ -171,33 +171,10 @@ void connect_ssl(bufferevent *orig_bev, ssl_st *ssl, std::string hostname,
...
-                    tls_check_name(nullptr, server_cert, hostname.c_str());
-                X509_free(server_cert);
-                if (hostname_validate_err != 0) {
-                    logger->debug("ssl: got invalid hostname");
+                err = libssl::verify_peer(hostname, ssl, logger);
+                if (err) {
                     bufferevent_free(bev);
-                    cb(SslInvalidHostnameError(), nullptr);
+                    cb(err, nullptr);
                     return;
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: Block of code above factored as `libssl::verify_peer()`. We retain previous behavior of freeing `bev` on error.

File: src/libmeasurement_kit/net/connect.cpp [hunk 14]
```diff
@@ -141,8 +144,7 @@ void connect_ssl(bufferevent *orig_bev, ssl_st *ssl, std::string hostname,
                  Var<Logger> logger) {
     logger->debug("connect ssl...");
 
-    // Perhaps DEFER not needed on SSL but setting it won't hurt. See
-    // the similar comment in connect_impl.hpp for rationale.
+    // See similar comment in connect_impl.hpp for rationale.
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: Actually `DEFER` was _needed_ also with SSL. So, corrected the comment.

File: src/libmeasurement_kit/net/connect.cpp [hunk 15]
```diff
@@ -5,14 +5,17 @@
 #ifdef HAVE_CONFIG_H
 #include "config.h" // For MK_CA_BUNDLE
 #endif
+#ifndef MK_CA_BUNDLE
+#error "MK_CA_BUNDLE is not set."
+#endif
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: I prefer the build to _fail_ if this is not set. If it does not fail, it silently proceeds and we _may_ end up with a library that does not work correctly because of this reason. This will require to update the Android build, BTW.

File: src/libmeasurement_kit/net/connect.cpp [hunk 16]
```diff
@@ -237,24 +214,13 @@ void connect(std::string address, int port,
                 return;
             }
             if (settings.find("net/ssl") != settings.end()) {
-                std::string cbp
-#ifdef MK_CA_BUNDLE
-                    = MK_CA_BUNDLE
-#endif
-                ;
+                std::string cbp = MK_CA_BUNDLE;
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: Now we know _for sure_ that `MK_CA_BUNDLE` is defined.

File: src/libmeasurement_kit/net/connect.cpp [hunk 17]
```diff
@@ -237,24 +214,13 @@ void connect(std::string address, int port,
...
-                if (!ssl_context) {
-                    Error err = ssl_context.as_error();
-                    bufferevent_free(r->connected_bev);
-                    callback(err, make_txp<Emitter>(
-                        timeout, r, reactor, logger));
-                    return;
-                }
-                ErrorOr<SSL *> cssl = (*ssl_context)->get_client_ssl(address);
+                ErrorOr<SSL *> cssl = libssl::Cache<>::thread_local_instance()
+                    .get_client_ssl(cbp, address, logger);
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: Code simplified. Now we use a single thread-safe operation to construct the `SSL *`. As commented originally in #1296, we really don't even need to see the `SSL_CTX *`. So, the API is such that we don't actually see it.

File: src/libmeasurement_kit/net/connect.cpp [hunk 18]
```diff
@@ -273,10 +239,10 @@ void connect(std::string address, int port,
                 }
                 if (*allow_ssl23 == true) {
                     logger->info("Re-enabling SSLv2 and SSLv3");
-                    SSL_clear_options(*cssl, SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3);
+                    libssl::enable_v23(*cssl);
```
Comment (bassosimone) [inline src/libmeasurement_kit/net/connect.cpp]: Refactored mostly for consistency: let's move all SSL code in the same place.

**Comment by bassosimone** [comment]
Since this is a refactoring, I've added cross references so to help reading the diff.

**Comment by bassosimone** [comment]
(Closed by error)

**Comment by bassosimone** [comment]
The proper milestone is `v0.7.1` even though this is developed for master. A backport will follow. I want to target master and then backport because this seems cleaner to me.

File: include/private/net/libssl.hpp [hunk 19]
```diff
@@ -0,0 +1,331 @@
...
+#if (defined LIBRESSL_VERSION_NUMBER && LIBRESSL_VERSION_NUMBER >= 0x2010400fL)
+                                          ,
+              MK_MOCK(SSL_CTX_load_verify_mem)
+#endif
+              >
+    static ErrorOr<Var<Context>> make(std::string ca_bundle_path,
+                                      Var<Logger> logger) {
+        // Implementation note: we need to get the library singleton as early
+        // as here to make sure OpenSSL internals are initialized.
+        auto library = Library::global();
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: @hellais reading again my diff, I started wondering whether it could happen that a compiler optimizes away the ``library` variable, since it is not used. We actually only get the singleton for its side effect; i.e. initializing the SSL library.

This pattern of creating a singleton only for its side effect is also used in other places in the library.

I have not worried about this, so far, because compilers I use do not complain about the variable being unused, and because things seems to be still working well.

What is your opinion on that?

Should I refactor this and the other places where this pattern is used, so to avoid this potential problem?

To help understanding the impact:

- if the SSL library is not properly initialized, depending on its version, it will not work (i.e. all calls will fail)

- we use the pattern also for libevent, to make sure locking is initialized; in such case, if the call is optimized away, libevent objects would not be thread safe (which is potentially a catastrophe).

File: include/private/net/libssl.hpp [hunk 20]
```diff
@@ -0,0 +1,331 @@
...
+            }
+        } else {
+#if (defined LIBRESSL_VERSION_NUMBER && LIBRESSL_VERSION_NUMBER >= 0x2010400fL)
+            std::vector<uint8_t> bundle = builtin_ca_bundle();
+            logger->debug("ssl: using builtin libressl's ca bundle");
+            if (!SSL_CTX_load_verify_mem(ctx, bundle.data(), bundle.size())) {
+                logger->warn("ssl: failed to load default ca bundle");
+                SSL_CTX_free(ctx);
+                return SslCtxLoadVerifyMemError();
+            }
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: Note: we currently don't have coverage of this section. To have it, we need to link against libressl. (Or, has OpenSSL picked up this libressl function? Or, can I write a diff for OpenSSL that ports this function?)

File: include/private/net/libssl.hpp [hunk 21]
```diff
@@ -0,0 +1,331 @@
...
+        */
+        if (all_.size() >= max_cache_size) {
+            logger->warn("ssl: hit hard limit of maximum cached SSL_CTX");
+            all_.clear();
+        }
+        if (all_.count(ca_bundle_path) == 0) {
+            ErrorOr<Var<Context>> maybe_context =
+                  Context::make(ca_bundle_path, logger);
+            if (!maybe_context) {
+                return maybe_context.as_error();
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: This case is not covered by the unit tests. To cover it, we need to wrap `Context::make` into an inline function and make the current method a template using that function or another function with same signature. That seems easy.

File: include/private/net/libssl.hpp [hunk 22]
```diff
@@ -0,0 +1,331 @@
...
+template <MK_MOCK(SSL_get_verify_result), MK_MOCK(SSL_get_peer_certificate),
+          MK_MOCK(tls_check_name)>
+Error verify_peer(std::string hostname, SSL *ssl, Var<Logger> logger) {
+    assert(ssl != nullptr);
+    logger->debug("SSL version: %s", SSL_get_version(ssl));
+    long verify_err = SSL_get_verify_result(ssl);
+    if (verify_err != X509_V_OK) {
+        logger->warn("ssl: got an invalid certificate");
+        return SslInvalidCertificateError(
+              X509_verify_cert_error_string(verify_err));
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: TODO: I should add mocks to cover this failure case.

File: include/private/net/libssl.hpp [hunk 23]
```diff
@@ -0,0 +1,331 @@
...
+    }
+    X509 *server_cert = SSL_get_peer_certificate(ssl);
+    if (server_cert == nullptr) {
+        logger->warn("ssl: got no certificate");
+        return SslNoCertificateError();
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: TODO: I should add mocks to cover this failure case.

**Comment by bassosimone** [comment]
Regress tests are failing. I believe this happens because of the combined effects of #1297 and of this pull request. The leaked bits of memory are thread-local storage. My guess is that this happens because we're running tasks in _detached_ threads. So the program terminates while they're not done yet.

Example of leak [taken from one of the failed runs](https://travis-ci.org/measurement-kit/measurement-kit/jobs/269983289#L3129):

```
FAIL: test/nettests/tcp_connect
===============================

==20745== Memcheck, a memory error detector
==20745== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==20745== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==20745== Command: ./test/nettests/tcp_connect
==20745== 
Contacting bouncer: https://bouncer.ooni.io
Your public IP address: 35.188.169.100
Your country: US
Your ISP identifier: AS15169
Results collector: https://b.collector.test.ooni.io:4441
Opening report; please be patient...
Report ID: 20170830T131556Z_AS15169_qVAs6t0PBKZIkvNltNx9xfMtWkyXEehXp4qgAyNjqie23SY7ZC
Submitting test results; please be patient...
Submitting test results; please be patient...
Submitting test results; please be patient...
Results successfully submitted
Submitting test results; please be patient...
Results successfully submitted
Results successfully submitted
Submitting test results; please be patient...
Submitting test results; please be patient...
Results successfully submitted
Submitting test results; please be patient...
Results successfully submitted
Results successfully submitted
Submitting test results; please be patient...
Submitting test results; please be patient...
Results successfully submitted
Results successfully submitted
Submitting test results; please be patient...
Results successfully submitted
Results successfully submitted
Closing report; please be patient...
Report successfully closed
[!] reactor: no pending and/or active events
===============================================================================
test cases: 1 | 1 passed
assertions: - none -

==20745== 
==20745== HEAP SUMMARY:
==20745==     in use at exit: 238,895 bytes in 6,031 blocks
==20745==   total heap usage: 227,450 allocs, 221,419 frees, 22,139,541 bytes allocated
==20745== 
==20745== 288 bytes in 1 blocks are possibly lost in loss record 610 of 696
==20745==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20745==    by 0x4013BAA: allocate_dtv (dl-tls.c:322)
==20745==    by 0x4013BAA: _dl_allocate_tls (dl-tls.c:539)
==20745==    by 0x678929B: allocate_stack (allocatestack.c:586)
==20745==    by 0x678929B: pthread_create@@GLIBC_2.2.5 (pthread_create.c:663)
==20745==    by 0x4DC235: std::__1::thread::thread<mk::Worker::run_in_background_thread(std::__1::function<void ()>&&)::{lambda()#1}&, , void>(mk::Worker::run_in_background_thread(std::__1::function<void ()>&&)::{lambda()#1}&) (in /mk/test/nettests/tcp_connect)
==20745==    by 0x4D9AFB: mk::Worker::run_in_background_thread(std::__1::function<void ()>&&) (in /mk/test/nettests/tcp_connect)
==20745==    by 0x4D1429: mk::nettests::start_internal_(mk::Var<mk::nettests::Runnable>&&, std::__1::promise<void>*, std::__1::function<void ()>&&) (in /mk/test/nettests/tcp_connect)
==20745==    by 0x4D12A0: mk::nettests::BaseTest::run() (in /mk/test/nettests/tcp_connect)
==20745==    by 0x429611: ____C_A_T_C_H____T_E_S_T____0() (in /mk/test/nettests/tcp_connect)
==20745==    by 0x4355B2: Catch::FreeFunctionTestCase::invoke() const (in /mk/test/nettests/tcp_connect)
==20745==    by 0x4163AC: Catch::TestCase::invoke() const (in /mk/test/nettests/tcp_connect)
==20745==    by 0x45341C: Catch::RunContext::invokeActiveTestCase() (in /mk/test/nettests/tcp_connect)
==20745==    by 0x452B35: Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (in /mk/test/nettests/tcp_connect)
==20745== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   fun:allocate_dtv
   fun:_dl_allocate_tls
   fun:allocate_stack
   fun:pthread_create@@GLIBC_2.2.5
   fun:_ZNSt3__16threadC2IRZN2mk6Worker24run_in_background_threadEONS_8functionIFvvEEEEUlvE_JEvEEOT_DpOT0_
   fun:_ZN2mk6Worker24run_in_background_threadEONSt3__18functionIFvvEEE
   fun:_ZN2mk8nettestsL15start_internal_EONS_3VarINS0_8RunnableEEEPNSt3__17promiseIvEEONS5_8functionIFvvEEE
   fun:_ZN2mk8nettests8BaseTest3runEv
   fun:_ZL29____C_A_T_C_H____T_E_S_T____0v
   fun:_ZNK5Catch20FreeFunctionTestCase6invokeEv
   fun:_ZNK5Catch8TestCase6invokeEv
   fun:_ZN5Catch10RunContext20invokeActiveTestCaseEv
   fun:_ZN5Catch10RunContext14runCurrentTestERNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES8_
}
==20745== LEAK SUMMARY:
==20745==    definitely lost: 0 bytes in 0 blocks
==20745==    indirectly lost: 0 bytes in 0 blocks
==20745==      possibly lost: 288 bytes in 1 blocks
==20745==    still reachable: 238,607 bytes in 6,030 blocks
==20745==         suppressed: 0 bytes in 0 blocks
==20745== Reachable blocks (those to which a pointer was found) are not shown.
==20745== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==20745== 
==20745== For counts of detected and suppressed errors, rerun with: -v
==20745== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
FAIL test/nettests/tcp_connect (exit status: 1)
```

**Comment by bassosimone** [comment]
Hmm, even with fix 158a79d applied, tests still fail. Re-reading the reason why they fail, I _still_ think the failure is caused by thread-local storage not being correctly freed. Probably the fix was not enough.

I am wondering whether it would make sense, instead, to just ignore leaks caused by thread local storage.

**Comment by bassosimone** [comment]
> I am wondering whether it would make sense, instead, to just ignore leaks caused by thread local storage.

But, actually, I don't like to do this, as it can hide more bugs.

**Comment by bassosimone** [comment]
Moved back to `in progress` queue, since this tests-failing issue prevent proper review.

**Comment by bassosimone** [comment]
Okay: at this point it is clear that I fixed the regress tests. Adding a couple more comments, re-reading the diff, and &mdash; unless I see anything weird &mdash; moving again in "ready for review" state.

File: include/private/net/libssl.hpp [hunk 24]
```diff
@@ -0,0 +1,331 @@
...
+            logger->warn("ssl: failed to create SSL_CTX");
+            return SslCtxNewError();
+        }
+        /*
+         * Implementation note:
+         *
+         * We use SSLv23_client_method() because it is the most general method
+         * that applications SHOULD use according to the manual[1] and we
+         * disable by default deprecated protocols. We MAY want to enable them
+         * in the OONI's web_connectivity test so to reach more websites.
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: We actually _do_ that. Maybe I can update this comment as part of merging the PR.

File: include/private/net/libssl.hpp [hunk 25]
```diff
@@ -0,0 +1,331 @@
...
+        }
+        Var<Context> context = all_[ca_bundle_path];
+        return context->get_client_ssl(hostname, logger);
+    }
+
+    /// Return number of cached SSL_CTX
+    size_t size() const { return all_.size(); }
+
+    /// Constructor
+    // Note: this is public to allow for testing
```
Comment (bassosimone) [inline include/private/net/libssl.hpp]: We can probably perform testing even if this is private (as I would like it to be)

File: test/nettests/dash.cpp [hunk 26]
```diff
@@ -12,7 +12,7 @@ using namespace mk::nettests;
 #ifdef ENABLE_INTEGRATION_TESTS
 
 TEST_CASE("Synchronous dash test") {
-    test::nettests::make_test<DashTest>().run();
+    test::nettests::with_test<DashTest>(test::nettests::run_test);
```
Comment (bassosimone) [inline test/nettests/dash.cpp]: From here onwards: I needed to rewrite some tests to make sure we wait for background threads to terminate, so that the thread local storage associated with them has been cleared. Otherwise Valgrind complains.

File: include/private/net/libssl.hpp (hunk 20 above)
Comment (bassosimone) [reply include/private/net/libssl.hpp]: For now, I guess we can ignore this problem.

File: include/private/net/libssl.hpp (hunk 22 above)
Comment (bassosimone) [reply include/private/net/libssl.hpp]: Done!

File: include/private/net/libssl.hpp (hunk 23 above)
Comment (bassosimone) [reply include/private/net/libssl.hpp]: Done!

File: include/private/net/libssl.hpp (hunk 12 above)
Comment (bassosimone) [reply include/private/net/libssl.hpp]: Done!

**Comment by bassosimone** [comment]
`libssl.hpp` has now [100% of coverage](https://coveralls.io/builds/13116200/source?filename=include%2Fprivate%2Fnet%2Flibssl.hpp).

File: src/libmeasurement_kit/net/connect.cpp (hunk 17 above)
Comment (hellais) [reply src/libmeasurement_kit/net/connect.cpp]: If I understand correctly this is actually the key to the solution of the bug, correct?

**Comment by hellais** [comment]
The diff looks good to me, though I did not read it super carefully.

In the future I think that it would be optimal that when addressing bugs (like in this case the thread safety issue with SSL), refactoring is done separately otherwise it makes reading the diff and understanding the bug very difficult.

If you want to do refactoring as part of the solution that is great 👍 , though it's best if you aim for first fixing the bug with the minimum number of code changes make a commit and note that is the bugfix and then proceed to doing refactoring as part of other commits.

**Comment by bassosimone** [comment]
> In the future I think that it would be optimal that when addressing bugs (like in this case the thread safety issue with SSL), refactoring is done separately otherwise it makes reading the diff and understanding the bug very difficult.

Yes, I agree. Thank you for the review!

**Comment by bassosimone** [comment]
Most tests passed, coverage still in progress. I am going to merge.
