### PR TITLE
Make dns callback robust to exceptions

### LINKED ISSUE #481: Make dns_callback robust to exceptions
When the [dns call the user callback](https://github.com/measurement-kit/measurement-kit/blob/master/src/dns/query.hpp#L205) it doesn't catch the possible exception that the callback can throw!

### PR DESCRIPTION
**Pull request by AntonioLangiu**
As found by @bassosimone, we didn't consider the case a user callback throws an exception. 
I think this should fix the problem and catch all the exception. 

@bassosimone do you know how to test if the context has been really deleted? 

This closes #481

### CODE REVIEW

File: src/dns/query.hpp [hunk 1]
```diff
@@ -201,13 +201,17 @@ static void dns_callback(int code, char type, int count, int ttl,
...
+    try {
+        if (context->message.error_code != DNS_ERR_NONE) {
+            context->callback(mk::dns::dns_error(context->message.error_code),
+                    context->message);
+        } else {
+            context->callback(NoError(), context->message);
+        }
+    } catch (const std::exception& e) {
+        delete context;
+        throw;
```
Comment (bassosimone) [inline src/dns/query.hpp]: I am undecided whether we should propagate exceptions here. I think we should stop here some exceptions, namely the ones derived from `Error` that MK users would probably like to throw. Other exceptions should probably continue because typically they indicate either errors external to MK or very serious conditions.

**Comment by bassosimone** [comment]
Moved to 0.3.0 because this is not priority for the upcoming release.

File: src/dns/query.hpp [hunk 2]
```diff
@@ -203,13 +203,17 @@ static void dns_callback(int code, char type, int count, int ttl,
...
-    } else {
-        context->callback(NoError(), context->message);
+    try {
+        if (context->message.error_code != DNS_ERR_NONE) {
+            context->callback(mk::dns::dns_error(context->message.error_code),
+                    context->message);
+        } else {
+            context->callback(NoError(), context->message);
+        }
+    } catch (const Error& e) {
```
Comment (bassosimone) [inline src/dns/query.hpp]: Good for [using const](http://stackoverflow.com/questions/2145147/why-catch-an-exception-as-reference-to-const)! We should use it in more places!
